### PR TITLE
Let requests manage param formatting, style cleanup

### PR DESCRIPTION
**Pull request by calebgroom**
- Removes string formatting for request parameters. Uses `requests` use of the `params` dict.
- Flake8/Pylint cleanup based on OpenStack `HACKING` style guidelines.
- Slack code was for our hackday testing. Dropping it.

You should assume that none of this has been tested and CYA before you merge ;)

### CODE REVIEW

**Comment by Linuturk** [comment]
Looks good. I had no idea about passing a params dictionary to requests. That's pretty cool. The only thing I'd have contention with is the use of `%` instead of the `.format()` string option. Going forward into Python 3, `.format()` is going to be the convention. Was there a particular reason you used `%` instead?

**Comment by calebgroom** [comment]
That's fair. Just old habit. I've pushed a change that reverts to `string.format()`. 

Same CYA exists, this is untested.

**Comment by Linuturk** [comment]
Just tested, works well. Thanks!

**Comment by calebgroom** [comment]
Awesome. Can you open a PR to send back upstream?

**Comment by Linuturk** [comment]
@calebgroom I've got one pending for Ryan's fork here: https://github.com/ryandub/st2contrib/pull/13 This hasn't been fully packed up yet as a proper st2 pack.

**Pull request merged**
